apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-persistent-storage #changed
  namespace: default #added
  labels:
    type: local
spec:
  capacity:
    storage: 100Gi #changed
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/mongodb" #changed
